Refactor: Remove type hints from release 4.1.3 so this is compatible with php 7.3
lanlin/nylas-php pull request #21
Opened 2020-09-03 13:09 UTC by jeremygriffin

Because I can not update my application to php7.4 just yet, I am proposing this as release version 3.6.0.

I re-forked and rebased my work on branch 3.0.

2020-09-04 02:23 UTC, lanlin approved these changes

2020-09-04 02:37 UTC, lanlin requested changes
@jeremygriffin you should not change the "commit with" option in the [codequality.yml](https://github.com/lanlin/nylas-php/pull/21/files/05f29a83c6138ea7a19f6ae097a2b744ff37b4e7#diff-a2fec8685580b06ea105ce239ffaff12), neither the "authors" option in the [composer.json](https://github.com/lanlin/nylas-php/pull/21/files/05f29a83c6138ea7a19f6ae097a2b744ff37b4e7#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)

2020-09-07 01:52 UTC, closed without merging

2020-09-07 01:56 UTC, lanlin commented
@jeremygriffin https://github.com/lanlin/nylas-php/releases/tag/3.6.0

2020-09-08 21:21 UTC, jeremygriffin commented
@lanlin I see you made the changes in your own commit.  Thanks for doing that.

I see that the codequality.yml is right with respect to you being the actor for push to master, I had changed it out of concern that in my fork that information would be incorrect and misleading.